{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"none","dataSources":[{"sourceId":225031124,"sourceType":"kernelVersion"}],"dockerImageVersionId":30918,"isInternetEnabled":false,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"Que1. Explain why we have to use the Exception class while creating a Custom Exception.\n\nAns1. We inherit exception class while creating a custom exception, because Exception\nis the base class for all built-in exceptions. By inheriting the exception class, our custom\nexception class inherits it`s properties due to which custom exception can be raised, caught, \nand handled just like any other built-in exception.\n\n","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"Q2. Write a python program to print Python Exception Hierarchy.","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"import inspect\n\ndef print_exception_hierarchy(cls, level=0):\n    \"\"\"Recursively prints the exception class hierarchy.\"\"\"\n    print('  ' * level + cls.__name__)\n    for subclass in cls.__subclasses__():\n        print_exception_hierarchy(subclass, level + 1)\n\n# Starting with the base Exception class\nprint(\"Python Exception Hierarchy:\")\nprint_exception_hierarchy(Exception)","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-05T05:23:17.590271Z","iopub.execute_input":"2025-03-05T05:23:17.590645Z","iopub.status.idle":"2025-03-05T05:23:17.675914Z","shell.execute_reply.started":"2025-03-05T05:23:17.590615Z","shell.execute_reply":"2025-03-05T05:23:17.675079Z"}},"outputs":[{"name":"stdout","text":"Python Exception Hierarchy:\nException\n  TypeError\n    InvalidType\n    MultipartConversionError\n    FloatOperation\n    DTypePromotionError\n    UFuncTypeError\n      UFuncTypeError\n        UFuncTypeError\n      UFuncTypeError\n        UFuncTypeError\n        UFuncTypeError\n    ConversionError\n  StopAsyncIteration\n  StopIteration\n  ImportError\n    ModuleNotFoundError\n      PackageNotFoundError\n    ZipImportError\n  OSError\n    ConnectionError\n      BrokenPipeError\n      ConnectionAbortedError\n      ConnectionRefusedError\n      ConnectionResetError\n        RemoteDisconnected\n    BlockingIOError\n    ChildProcessError\n    FileExistsError\n    FileNotFoundError\n      ExecutableNotFoundError\n    IsADirectoryError\n    NotADirectoryError\n    InterruptedError\n      InterruptedSystemCall\n    PermissionError\n    ProcessLookupError\n    TimeoutError\n    UnsupportedOperation\n    itimer_error\n    OSError\n    herror\n    gaierror\n    SSLError\n      SSLCertVerificationError\n      SSLZeroReturnError\n      SSLWantWriteError\n      SSLWantReadError\n      SSLSyscallError\n      SSLEOFError\n    Error\n      SameFileError\n    SpecialFileError\n    ExecError\n    ReadError\n    URLError\n      HTTPError\n      ContentTooShortError\n    BadGzipFile\n    UnidentifiedImageError\n  EOFError\n    IncompleteReadError\n  RuntimeError\n    RecursionError\n    NotImplementedError\n      StdinNotImplementedError\n      ZMQVersionError\n    _DeadlockError\n    BrokenBarrierError\n    BrokenExecutor\n      BrokenThreadPool\n    SendfileNotAvailableError\n    RemovedCommandError\n    PackageDiscoveryError\n    TooHardError\n  NameError\n    UnboundLocalError\n  AttributeError\n    FrozenInstanceError\n  SyntaxError\n    IndentationError\n      TabError\n    ParseError\n  LookupError\n    IndexError\n      AxisError\n      OutOfBounds\n    KeyError\n      UnknownBackend\n      NoSuchKernel\n    CodecRegistryError\n  ValueError\n    UnicodeError\n      UnicodeEncodeError\n      UnicodeDecodeError\n      UnicodeTranslateError\n    UnsupportedOperation\n    JSONDecodeError\n    MalformedError\n    InvalidResource\n    InvalidOperation\n    InvalidValue\n    MessageDefect\n      NoBoundaryInMultipartDefect\n      StartBoundaryNotFoundDefect\n      CloseBoundaryNotFoundDefect\n      FirstHeaderLineIsContinuationDefect\n      MisplacedEnvelopeHeaderDefect\n      MissingHeaderBodySeparatorDefect\n      MultipartInvariantViolationDefect\n      InvalidMultipartContentTransferEncodingDefect\n      UndecodableBytesDefect\n      InvalidBase64PaddingDefect\n      InvalidBase64CharactersDefect\n      InvalidBase64LengthDefect\n      HeaderDefect\n        InvalidHeaderDefect\n        HeaderMissingRequiredValue\n        NonPrintableDefect\n        ObsoleteHeaderDefect\n        NonASCIILocalPartDefect\n        InvalidDateDefect\n    Error\n    IllegalMonthError\n    IllegalWeekdayError\n    SSLCertVerificationError\n    UnsupportedDigestmodError\n    ClassNotFound\n    ClipboardEmpty\n    MacroToEdit\n    ParserError\n    UnequalIterablesError\n    UnequalIterablesError\n    ELFInvalid\n    InvalidVersion\n    InvalidName\n    InvalidWheelFilename\n    InvalidSdistFilename\n    InvalidSpecifier\n    InvalidMarker\n    UndefinedComparison\n    UndefinedEnvironmentName\n    InvalidRequirement\n    AxisError\n    LinAlgError\n    DefusedXmlException\n      DTDForbidden\n      EntitiesForbidden\n      ExternalReferenceForbidden\n      NotSupportedError\n    NonIntersectingPathException\n  AssertionError\n  ArithmeticError\n    FloatingPointError\n    OverflowError\n    ZeroDivisionError\n      DivisionByZero\n      DivisionUndefined\n    DecimalException\n      Clamped\n      Rounded\n        Underflow\n        Overflow\n      Inexact\n        Underflow\n        Overflow\n      Subnormal\n        Underflow\n      DivisionByZero\n      FloatOperation\n      InvalidOperation\n        ConversionSyntax\n        DivisionImpossible\n        DivisionUndefined\n        InvalidContext\n  SystemError\n    CodecRegistryError\n  ReferenceError\n  MemoryError\n    MemoryError\n  BufferError\n  Warning\n    UserWarning\n      GetPassWarning\n      FormatterWarning\n      SetuptoolsWarning\n        InformationOnly\n        SetuptoolsDeprecationWarning\n          _AmbiguousMarker\n          _DeprecatedConfig\n          DistDeprecationWarning\n        _MissingDynamic\n        _ExperimentalConfiguration\n        _ToolsTypoInMetadata\n      VisibleDeprecationWarning\n      RankWarning\n      ConversionWarning\n      RankWarning\n    EncodingWarning\n    DeprecationWarning\n      Python37DeprecationWarning\n      ProvisionalWarning\n      ModuleDeprecationWarning\n      MatplotlibDeprecationWarning\n    PendingDeprecationWarning\n    SyntaxWarning\n    RuntimeWarning\n      ProactorSelectorThreadWarning\n      UnknownTimezoneWarning\n      ComplexWarning\n      DecompressionBombWarning\n    FutureWarning\n      ProvisionalCompleterWarning\n      MaskedArrayFutureWarning\n    ImportWarning\n    UnicodeWarning\n    BytesWarning\n    ResourceWarning\n    DeprecatedTzFormatWarning\n    MathTextWarning\n  _OptionError\n  error\n  Verbose\n  Error\n  TokenError\n  StopTokenizing\n  GoogleAuthError\n    TransportError\n    RefreshError\n      ReauthFailError\n        ReauthSamlChallengeFailError\n    UserAccessTokenError\n    DefaultCredentialsError\n      MalformedError\n      InvalidResource\n      InvalidOperation\n      InvalidValue\n      InvalidType\n      OSError\n    MutualTLSChannelError\n    ClientCertError\n    OAuthError\n  MessageError\n    MessageParseError\n      HeaderParseError\n        _InvalidEwError\n      BoundaryError\n    MultipartConversionError\n    CharsetError\n    HeaderWriteError\n  Incomplete\n  error\n  _GiveupOnSendfile\n  Error\n  HTTPException\n    NotConnected\n    InvalidURL\n    UnknownProtocol\n    UnknownTransferEncoding\n    UnimplementedFileMode\n    IncompleteRead\n    ImproperConnectionState\n      CannotSendRequest\n      CannotSendHeader\n      ResponseNotReady\n    BadStatusLine\n      RemoteDisconnected\n    LineTooLong\n  ClassFoundException\n  EndOfBlock\n  _Error\n  SubprocessError\n    CalledProcessError\n    TimeoutExpired\n  Error\n  error\n  LZMAError\n  RegistryError\n  _GiveupOnFastCopy\n  TraitError\n  PickleError\n    PicklingError\n    UnpicklingError\n  _Stop\n  Empty\n  Full\n  ArgumentError\n  ArgumentTypeError\n  ConfigError\n    ConfigLoaderError\n      ArgumentError\n    ConfigFileNotFound\n  ConfigurableError\n    MultipleInstanceError\n  ApplicationError\n  ErrorDuringImport\n  BdbQuit\n  Restart\n  ExceptionPexpect\n    EOF\n    TIMEOUT\n  error\n  PtyProcessError\n  FindCmdError\n  HomeDirError\n  ProfileDirError\n  IPythonCoreError\n    TryNext\n    UsageError\n    StdinNotImplementedError\n  InputRejected\n  GetoptError\n  Error\n  BadZipFile\n  LargeZipFile\n  OptionError\n  ErrorToken\n  PrefilterError\n  AliasError\n    InvalidAliasError\n  Error\n    InterfaceError\n    DatabaseError\n      InternalError\n      OperationalError\n      ProgrammingError\n      IntegrityError\n      DataError\n      NotSupportedError\n  Warning\n  Error\n    CancelledError\n    TimeoutError\n    InvalidStateError\n  TimeoutError\n  InvalidStateError\n  LimitOverrunError\n  QueueEmpty\n  QueueFull\n  SpaceInInput\n  DOMException\n    IndexSizeErr\n    DomstringSizeErr\n    HierarchyRequestErr\n    WrongDocumentErr\n    InvalidCharacterErr\n    NoDataAllowedErr\n    NoModificationAllowedErr\n    NotFoundErr\n    NotSupportedErr\n    InuseAttributeErr\n    InvalidStateErr\n    SyntaxErr\n    InvalidModificationErr\n    NamespaceErr\n    InvalidAccessErr\n    ValidationErr\n  ValidationError\n  EditReadOnlyBuffer\n  _Retry\n  InvalidLayoutError\n  HeightIsUnknownError\n  ExpatError\n  ParseEscape\n  ParserSyntaxError\n  InternalParseError\n  _PositionUpdatingFinished\n  ArgumentError\n  SimpleGetItemNotFound\n  UncaughtAttributeError\n  HasNoContext\n  ParamIssue\n  _JediError\n    InternalError\n    WrongVersion\n    RefactoringError\n  OnErrorLeaf\n  InvalidPythonEnvironment\n  InteractivelyDefined\n  KillEmbedded\n  ZMQBaseError\n    ZMQError\n      ContextTerminated\n      Again\n      InterruptedSystemCall\n    ZMQBindError\n    NotDone\n  error\n  ReturnValueIgnoredError\n  KeyReuseError\n  UnknownKeyError\n  LeakedCallbackError\n  BadYieldError\n  ReturnValueIgnoredError\n  Return\n  InvalidPortNumber\n  Error\n    NoSectionError\n    DuplicateSectionError\n    DuplicateOptionError\n    NoOptionError\n    InterpolationError\n      InterpolationMissingOptionError\n      InterpolationSyntaxError\n      InterpolationDepthError\n    ParsingError\n      MissingSectionHeaderError\n  NoIPAddresses\n  DuplicateKernelError\n  QueueEmpty\n  QueueFull\n  IPythonError\n    KernelError\n      EngineError\n      NoEnginesRegistered\n      TaskAborted\n      TaskTimeout\n      UnmetDependency\n        ImpossibleDependency\n          DependencyTimeout\n          InvalidDependency\n      RemoteError\n        CompositeError\n        AlreadyDisplayedError\n      TaskRejectError\n  ProcessError\n    BufferTooShort\n    TimeoutError\n    AuthenticationError\n  BadEntryPoint\n  NoSuchEntryPoint\n  Error\n    NoSuchProcess\n      ZombieProcess\n    AccessDenied\n    TimeoutExpired\n  _Ipv6UnsupportedError\n  LauncherError\n    ProcessStateError\n    UnknownStatus\n    NotRunning\n  DistutilsError\n    DistutilsModuleError\n    DistutilsClassError\n    DistutilsGetoptError\n    DistutilsArgError\n    DistutilsFileError\n    DistutilsOptionError\n      InvalidConfigError\n      RemovedConfigError\n    DistutilsSetupError\n    DistutilsPlatformError\n    DistutilsExecError\n    DistutilsInternalError\n    DistutilsTemplateError\n    DistutilsByteCompileError\n    RemovedCommandError\n    PackageDiscoveryError\n  CCompilerError\n    PreprocessError\n    CompileError\n    LibError\n    LinkError\n    UnknownFileError\n  TarError\n    ExtractError\n    ReadError\n    CompressionError\n    StreamError\n    HeaderError\n      EmptyHeaderError\n      TruncatedHeaderError\n      EOFHeaderError\n      InvalidHeaderError\n      SubsequentHeaderError\n    FilterError\n      AbsolutePathError\n      OutsideDestinationError\n      SpecialFileError\n      AbsoluteLinkError\n      LinkOutsideDestinationError\n  ParserSyntaxError\n  ConverterError\n    ConverterLockError\n  MAError\n    MaskError\n  DecompressionBombError\n  ParseBaseException\n    ParseException\n    ParseFatalException\n      ParseSyntaxException\n  RecursiveGrammarException\n  _ParseActionIndexError\n  BadRequiredStrength\n  DuplicateConstraint\n  DuplicateEditVariable\n  UnknownConstraint\n  UnknownEditVariable\n  UnsatisfiableConstraint\n  NonGuiException\n  InvalidIndexError\n  TerminateTrajectory\n","output_type":"stream"}],"execution_count":18},{"cell_type":"code","source":"Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n\nAns3: The errors defined in ArithmeticError class are as follows:\n1. ZeroDivisionError\n2. OverflowError\n3. FloatingPointError\n4. DecimalError (if using the decimal module)\n\n\n","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"#ZeroDivisionError:\n#Although it is not best practise to use superclass for handling the exception, however we\n# are using superclass ArithmeticError for exception handling because the question is regarding\n# ArithmeticError class.\n\ntry:\n    a=10/0\nexcept ArithmeticError as e:\n    print(e)\n\n","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-05T04:48:03.472207Z","iopub.execute_input":"2025-03-05T04:48:03.472565Z","iopub.status.idle":"2025-03-05T04:48:03.478198Z","shell.execute_reply.started":"2025-03-05T04:48:03.472539Z","shell.execute_reply":"2025-03-05T04:48:03.477110Z"}},"outputs":[{"name":"stdout","text":"division by zero\n","output_type":"stream"}],"execution_count":1},{"cell_type":"code","source":"#  OverflowError\n\"\"\"An OverflowError occurs when a numeric operation produces a result that is too large to\nbe represented within the allowable range for that numeric type.\"\"\"\n\ntry:\n    num=10**10000\nexcept OverflowError as e:\n    print(e)\n","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-05T04:55:37.293712Z","iopub.execute_input":"2025-03-05T04:55:37.294088Z","iopub.status.idle":"2025-03-05T04:55:37.298518Z","shell.execute_reply.started":"2025-03-05T04:55:37.294056Z","shell.execute_reply":"2025-03-05T04:55:37.297551Z"}},"outputs":[],"execution_count":9},{"cell_type":"code","source":"Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n\nAns4. The LookupError class in Python is a base class for exceptions that are raised when\na lookup operation (such as accessing a key in a dictionary or an index in a list) fails. \nIt serves as a common parent class for more specific exceptions like KeyError and \nIndexError.","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"#Exmaple for KeyError:\nimport logging\nlogging.basicConfig(filename=\"error.log\",level=logging.ERROR)\ntry:\n    dic={\"abhi\":123,\"aman\":345,\"krishna\":908}\n    value=dic[\"anuj\"]\nexcept KeyError as e:\n    logging.error(\"Handling keyerror exception {}\".format(e))\n    print(e)","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-05T05:02:41.842223Z","iopub.execute_input":"2025-03-05T05:02:41.842635Z","iopub.status.idle":"2025-03-05T05:02:41.848040Z","shell.execute_reply.started":"2025-03-05T05:02:41.842601Z","shell.execute_reply":"2025-03-05T05:02:41.846972Z"}},"outputs":[{"name":"stdout","text":"'anuj'\n","output_type":"stream"}],"execution_count":13},{"cell_type":"code","source":"# Example for IndexError:\nimport logging\nlogging.basicConfig(filename=\"error.log\",level=logging.ERROR)\ntry:\n    l=[2,3,4]\n    print(l[7])\nexcept IndexError as e:\n    logging.error(\"Handline Index error here {}\".format(e))\n    print(e)","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-05T05:06:02.692701Z","iopub.execute_input":"2025-03-05T05:06:02.693017Z","iopub.status.idle":"2025-03-05T05:06:02.698591Z","shell.execute_reply.started":"2025-03-05T05:06:02.692993Z","shell.execute_reply":"2025-03-05T05:06:02.697536Z"}},"outputs":[{"name":"stdout","text":"list index out of range\n","output_type":"stream"}],"execution_count":17},{"cell_type":"code","source":"Q5. Explain ImportError. What is ModuleNotFoundError?\n\nAns5. ImportError is an exception that is raised when an imported module or a specific \nobject from a module cannot be found or loaded.\n\nModuleNotFoundError is a more specific subclass of ImportError that is raised when a \nmodule is not found during an import statement. This error is typically seen when the \nmodule you are trying to import does not exist in the current Python environment.\n\nIt was introduced in Python 3.6 to provide more clarity when dealing with module imports.\nBefore Python 3.6, ImportError was used to handle all import-related errors, \nincluding the case where a module could not be found. In Python 3.6 and later, \nModuleNotFoundError is raised when Python is unable to locate a module.","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"Q6. List down some best practices for exception handling in python.\nAns6. The best practices for exception handling in python are as follows:\n\n1. Always use a specific Exception: It is a good practise in python to use the specific \nclass for handling an exception. For example: if we are handling a ZeroDivisionError then\ncan handle it with Exception or ArithmeticError class as well, however it is best to \nhandle it with ZeroDivisionError only.\n\n2. Always print a proper message in case exception occurs: It is always better to provide descriptive reason for the occurance of the exception,\nso that if any other person also working on the project, so they can identify easily what went \nwrong.\n\n3. Always try to log your error: This point is very similar to our previous point. Here,\nwe need to log the error so that other persons working on the project may figure out\nthe errors that occured while running the program. So that they can improvise the code easily.\n\n4. Always try to avoid multiple exception handling: Instead of using mulitple except blocks\n(or multiple exception classes), we need to use a single specific sub-class (not super class Exception)\nin order to handle the exception.\n\n5. Document all the errors: In an industry grade program, it is mandator that we document\nall the error and purpose of the modules that we made, so that our program or module \ncan be easily understood and improvised in the future.\n\n6. Clean up all the resources: While performing exception handling or writing the code,\nit is required that we relase all the resources used by the module while execution, once\nthe execution of module is finished.\nFor ex: When we open the file then it is mandatory to close it. So we generally close the\nfile in finally block so that the file can be closed in any case (even if the exception \noccurs).                                                                             \n                                                                             ","metadata":{"trusted":true},"outputs":[],"execution_count":null}]}